### ISSUE TITLE
change controller

### ISSUE THREAD

**Issue by vokshirg** [lml/commontator#100]
Hi, i need change comments_controller.rb. I've used `rake commontator:copy:controllers` it was copied controllers to /controllers/commontator, change comments_controller but it didn't take effect, what's wrong?
Thanks

**Comment by Dantemss** [comment]
Hello, did you make sure to completely restart the server process? If you did, it should just work...

**Comment by vokshirg** [comment]
Yes, of course i restarted it, but the same
my env: ruby 2.2.1 Rails 4.2.5.1

**Comment by vokshirg** [comment]
oh sorry it was my mistake
