### ISSUE TITLE
Using commontator with clearance

### ISSUE THREAD

**Issue by aronstrandberg** [lml/commontator#102]
I'm having some trouble getting commontator to work with [thoughtbot/clearance](https://github.com/thoughtbot/clearance). It seems that clearance doesn't expose a public `current_user` method on the controllers. 
The error i'm getting is:
```
private method `current_user' called for #<BeersController:0x007fefe3375430>
```

My `current_user_proc` is the default one. I'm using the `current_user` method on several places in the controller, so it does exist. 
`config.current_user_proc = lambda { |controller| controller.current_user }`

It might also be me being stupid, but would appreciate some guidance either way! Thanks.

**Comment by Dantemss** [comment]
Try using `controller.send :current_user` to get around the private method limitation I suppose.
