### ISSUE TITLE
undefined method `thread' for nil:NilClass

### ISSUE THREAD

**Issue by dsCloud** [lml/commontator#103]
Hello.....
Please I have this same issue right now. After following the instruction, I did not add any other code. Any help on the additional code to add will be appreciated. My acts_as_commontable model is Feedback.
Thanks in advance

**Comment by Dantemss** [comment]
Could you post your backtrace? Or at least the first few lines of it?

**Comment by kohjingyu** [comment]
I had this problem, until I realised I was literally using `<%= commontator_thread(@commontable) %>` instead of `<%= commontator_thread(**@post**) %>`, where @post was my actual model.
