### ISSUE TITLE
Missing PNG assets precompilation statement for Sprockets

### ISSUE THREAD

**Issue by mlt** [lml/commontator#104]
I'm a noob, but adding

``` rb
Rails.application.config.assets.precompile += %w( *.png )
```

to `./config/initializers/assets.rb` in deployed gem followed with `rake assets:precompile` resolved complains from Sprocket (Sprockets::Rails::Helper::AssetNotPrecompiled).
Before that, there was a suggestion for my app

```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( commontator/upvote_disabled.png )` to `config/initializers/assets.rb` and restart your server
```

I'm not 100% sure if that is the right way to approach things, otherwise I'd submit PR :sunglasses:

**Comment by Dantemss** [comment]
Will be fixed in 7.0.0 (fixed in 7.0.0.pre.1)
