### ISSUE TITLE
how to un install this gem ?

### ISSUE THREAD

**Issue by testpavan123** [lml/commontator#110]
rake commontator:install

this command installed many things , i gave rails db:migrate also . now i dont want to work on this and did rails db:rollback , now when i give 
rails db:migrate , following error is coming

rails aborted!
NameError: uninitialized constant Commontator
/home/vyshnavi/web16-10/project/config/initializers/commontator.rb:6:in `<top (required)>'
/home/vyshnavi/web16-10/project/config/environment.rb:5:in `<top (required)>'
/home/vyshnavi/web16-10/project/bin/rails:9:in `require'
/home/vyshnavi/web16-10/project/bin/rails:9:in `<top (required)>'
/home/vyshnavi/web16-10/project/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by testpavan123** [comment]
I even removed gem from gem file and uninstalled the installed gem also

**Comment by Dantemss** [comment]
Hello, I suggest running rake db:rollback and deleting the migration before you remove the gem.
From the error backtrace, it seems you forgot to delete the initializer in `config/initializers/commontator.rb`.

**Comment by testpavan123** [comment]
your suggestion worked sir. thanks :)
