### ISSUE TITLE
Theads div is display:hidden by default?

### ISSUE THREAD

**Issue by jmuheim** [lml/commontator#113]
The full thing is hidden initially:

![image](https://cloud.githubusercontent.com/assets/1814983/21924763/c02e84aa-d97a-11e6-9f3a-1f056ad399c8.png)

I have to change it manually in the DOM inspector so I see anything in the view. Have I forgotten something?

**Comment by aguxez** [comment]
Did you find a way to fix this? I could display it initially but every time when I click on 'Hide Comments' | 'Show comments' the div is hidden again.

**Comment by Dantemss** [comment]
You can add `commontator_thread_show(commontable_object)` to your controller to have the comments display immediately on load.
