### ISSUE TITLE
Comments not registered user

### ISSUE THREAD

**Issue by apasna0** [lml/commontator#114]
Hello,
I am working with this project, where admin is authenticated with devise gem. there is no registration for users. and i want to enable comments for not registered users to comment admin posts. Now, when i click on the link after my post show comments (0) it only writes me this: You must login before you can post a comment... and nothing happens. Where and how i can config my commontator gem, if anonymous user wants to comment a post?

**Comment by Dantemss** [comment]
I believe you could solve this by creating an AnonymousUser object:

```
class AnonymousUser
  include Singleton

  def name
    I18n.t('commontator.anonymous')
  end
end
```

And then in commontator.rb:

```
config.current_user_proc = lambda { |controller| controller.current_user || AnonymousUser.instance }

config.user_name_proc = lambda { |user| user.name }

config.thread_moderator_proc = lambda { |thread, user| user != AnonymousUser.instance }
```

I'm assuming your admin `User` model has a `name` field.

**Comment by apasna0** [comment]
so theres no simple way to let anyone write comments, without creating new objects?? strange...

**Comment by jfrux** [comment]
Would this affect a user's name from showing when other users aren't logged in?
Trying to figure out why a comment's "user" is only available when logged in...
