### ISSUE TITLE
Cannot get mentioning to work

### ISSUE THREAD

**Issue by sghata** [lml/commontator#116]
I've got everything setup and working perfectly except the user's mentioning feature:
```
config.mentions_enabled = false
config.user_mentions_proc = lambda { |user, query|
    user.class.where('username LIKE ?', "#{query}%") }
```
Whenever I enable mentions_enabled, I lose the ability to add a comment. I'm not sure if this is a Rails 5 issue.

**Comment by Dantemss** [comment]
Assuming you added `//= require commontator/application` to your application.js (before the first blank line), it should work. Yes, definitely could be a Rails 5 issue.

If you want to debug this issue, I recommend checking the browser console for JS errors after you try to comment.

**Comment by sghata** [comment]
I didn't add //= require commontator/application
Thank you for your help!
