### ISSUE TITLE
undefined method `thread' for #<Extra::ActiveRecord_Relation:0x00562cca878028>  Did you mean? third

### ISSUE THREAD

**Issue by yawarsultan** [lml/commontator#117]
I am getting this error. this is my view code
<%= commontator_thread(@extras) %>
this is my controller code
def top_ptc_sites
    @extras = Extra.all.order(:cached_votes_score => :desc)
     commontator_thread_show(@extras)
  end
why i am getting this error

**Comment by Dantemss** [comment]
I believe the issue is that you need to pick a single object from @extras, it won't work on the entire collection...
