### ISSUE TITLE
NoMethodError in commontator/threads # show

### ISSUE THREAD

**Issue by laranicolas** [lml/commontator#119]
Hey guys I'm having this issue repetead around 6K on site.

Message:
```
NoMethodError: undefined method `blog_post_path' for #<ActionDispatch::Routing::RoutesProxy:0x007feddd526f98>
35           send(method, *args)
36         else
37           super
38         end
39       end
```

**Comment by Dantemss** [comment]
I believe you might have to adjust the `comment_url_proc` in the config to point to the page where you want to display the comments. `comment.thread.commontable` should return the blog_post object (if that is the "commontable" object)

**Comment by AkiBeulah** [comment]
> I believe you might have to adjust the `comment_url_proc` in the config to point to the page where you want to display the comments. `comment.thread.commontable` should return the blog_post object (if that is the "commontable" object)

Sorry, I don't quite understand. I am having a similar issue. 
I don't know how to what `comment.thread.commontable` returns. I tried substituting it for the path itself `user_post` but that didn't work. So I am clearly lacking in understanding.
