### ISSUE TITLE
Rails 4 compatibility

### ISSUE THREAD

**Issue by Brotakuu** [lml/commontator#127]
Is commontator 5.1.0 compatible with Rails 4?

When using `gem 'commontator' , '~> 5.1.0'` in the gemfile, bundle install returns the following error:

```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 4.2.6)

  In Gemfile:
    rails (= 4.2.6)

    commontator (~> 5.1.0) was resolved to 5.1.0, which depends on
      rails (>= 5.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

However `commontator 4.11.1` works fine with Rails 4. But is it missing some functionality?

**Comment by Dantemss** [comment]
No, sorry, I think it was because Rails 5 added those mandatory [] in the migration class but I don't quite remember at this point.
