### ISSUE TITLE
Show Comments div style being set to "display: none;"

### ISSUE THREAD

**Issue by RobertACuthbert** [lml/commontator#128]
Hi, I am having an issue where my '<%= commontator_thread(feedback) %>' isn't displaying due to the style being `style="display: none;`. I expected this to add `Show Comments (2)` to my feedback table but it displays nothing. 

Example of the div created:
![image](https://user-images.githubusercontent.com/30883819/39554524-6a328998-4ec7-11e8-99fe-dd217368a620.png)

I've found that when I override the style it displays as expected. Two examples:

1. In `show.html.erb` by adding the following inline. 
`<style>
  div .thread  {
    display: block !important;
  }
</style>`

2. By adding the Commontator views to my project then In `_thread.html.erb` remove the 'style="display: none;"'
`<% if thread.can_be_read_by?(user) %>`
`<div id="thread_<%= thread.id %>_div" class="thread" style="display: none;">`
`<% if @commontator_thread_show %>`
to
`<% if thread.can_be_read_by?(user) %>`
`<div id="thread_<%= thread.id %>_div" class="thread">`
`<% if @commontator_thread_show %>`

I think there could be a bug in the logic here. It looks like for a user who has permission to view the comments this code is adding a style that does not display the comments. As I was debugging both `if` statements returned `true`.

**Comment by RobertACuthbert** [comment]
As you suggested to someone with a similar issue in #113 I added `commontator_thread_show(commontable_object)` to my feedbacks controller but `style="display: none;` is still being added.
```
  def show
    @feedback = Feedback.find(params[:id])
    commontator_thread_show(@feedback)
  end
```

**Comment by xuwupeng2000** [comment]
Same here on Rails 5

**Comment by Dantemss** [comment]
Sorry for the delay replying, the thread is hidden by default until the CSS loads. The line that overrides the style is this one: https://github.com/lml/commontator/blob/master/app/assets/stylesheets/commontator/threads.css#L2

If you'd prefer not to use the provided CSS, you can provide your own with the above style or override the view not to add the inline style.
