### ISSUE TITLE
How to set a user as a moderator/admin? 

### ISSUE THREAD

**Issue by seeuser** [lml/commontator#129]
I apologize if this seems a naive question

Ive read config file, and seems to be here... , but I cant figure it out. 
Ive searched through the other questions, nobody seems to have/had this problem.

      # thread_moderator_proc
      # Type: Proc
      # Arguments: a thread (Commontator::Thread), a user (acts_as_commontator)
      # Returns: a Boolean, true if and only if the user is a moderator for that thread
      # If you want global moderators, make this proc true for them regardless of thread
      # Default: ->(thread, user) { false } (no moderators)
      config.thread_moderator_proc = ->(thread, user) { false }

I understand I need to set this to true, but how do I set the user? 
for example: the user with id:1 as a moderator

**Comment by Dantemss** [comment]
Hello. Make the `thread_moderator_proc` return true for your moderators. In your case: `config.thread_moderator_proc = ->(thread, user) { user.id == 1 }`

But REALLY you don't want to rely on the user having id == 1 to be a moderator. I suggest adding a boolean field to either your users table or a separate table that you use for this purpose (for example: `config.thread_moderator_proc = ->(thread, user) { user.is_moderator }`

**Comment by seeuser** [comment]
Thanks, I now understand.
