### ISSUE TITLE
PG::UndefinedTable: ERROR:  relation "users" does not exist

### ISSUE THREAD

**Issue by rinkumohan** [lml/commontator#131]
while clicking on **Show Comments (0)** link
Processing by Commontator::ThreadsController#show as JS
  Parameters: {"id"=>"7"}

PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 1: SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDE...

: SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1):
  config/initializers/commontator.rb:15:in `block (2 levels) in <top (required)>'

**commontator.rb   (line.15)**
  `config.current_user_proc = lambda { |controller| controller.current_user }`

I am using Devise. It is given that the default works for Devise and similar authentication plugins

**Comment by Dantemss** [comment]
Seems you are missing the `users` table. Devise should help you get that setup.
