### ISSUE TITLE
not receiving subscription mails.

### ISSUE THREAD

**Issue by Amansingla97** [lml/commontator#132]
I apologize if this seems a naive question

Ive read instructions to follow to enable subscriptions.. I am able to subcribe and unsubscribe but when a person adds a comment to a subscribed post i am not recieving any mails .. what could be the possible reasons ?do we need a mailgun subscription?

It shows the following Argument error on sidekiq server
Please kindly check the syntax of views/subscriptions

**Comment by Dantemss** [comment]
Mailgun is not necessary. Are you able to send other emails from the same server? Also check if ActiveJob is properly setup since Rails 5 uses that to send email.
