### ISSUE TITLE
Conflict with existing subscription model

### ISSUE THREAD

**Issue by vaishnavi3** [lml/commontator#135]
If an existing model named Subscription is present we get a conflict that `subsription.thread_id ` does not exist.
It then refers to the app's Subscription model instead of Commontators Subsription model.
Detailed explanation can be found [here](https://stackoverflow.com/questions/55790830/work-around-for-apps-with-existing-subscription-model-when-using-commentator-gem)
How do I resolve this?

**Comment by Dantemss** [comment]
I think you can simply ensure Commontator::Subscription is loaded by calling it explicitly somewhere in your application. I will make a patch so Commontator uses the full namespaced model names.

**Comment by Dantemss** [comment]
Will be fixed in 6.0.0 (fixed in 6.0.0.pre.1)
