### ISSUE TITLE
Yarn (webpacker gem) support

### ISSUE THREAD

**Issue by alaarab** [lml/commontator#148]
Is the javascript for commontator available through Yarn? Any plans for this? Since Rails 6 does not ship with assets/javascripts, it would be good to have this.

Thanks.

**Comment by Dantemss** [comment]
Yes, it would be nice to support the webpacker gem.

**Comment by Dantemss** [comment]
Seems like webpacker does not support JS from gems, so the copy command is what we need. We can continue the discussion on that issue.
