### ISSUE TITLE
A bug in updating comment view when replies disabled

### ISSUE THREAD

**Issue by pustomytnyk** [lml/commontator#150]
Hi. Tried to setup gem on Rails 6. Something seem to be off with updating/deleting a comment when `config.comment_reply_style = :n`: after js-response it lists all comments as comment's children.  

![2019-10-07 172738](https://user-images.githubusercontent.com/9644824/66320823-39407500-e928-11e9-8c0f-54a53c760d06.png)

I tracked unexpected output to this [method ](https://github.com/lml/commontator/blob/c8d1a438a577bd4e83509cfcab00cce3c309b362/app/models/commontator/thread.rb#L63)where parent_id is ignored (id of comment being edited):
```
  def comments_with_parent_id(parent_id, show_all)
    oc = ordered_comments(show_all)
    [ :i, :b ].include?(config.comment_reply_style) ? oc.where(parent_id: parent_id) : oc
  end
```
Works as expected with, say, `config.comment_reply_style = :i`.
Shouldn't it always consider parent_id or have checking on erb-template? Or this may be some my misconfiguration?

**Comment by pustomytnyk** [comment]
I reproduced it in minimal app, so definitely a bug 🐞

**Comment by Dantemss** [comment]
I pushed version 6.1.1 with a fix, please give it a try.

**Comment by pustomytnyk** [comment]
@Dantemss nice, works as expected.
