### ISSUE TITLE
Using helper method in comments/_body.html.erb

### ISSUE THREAD

**Issue by 1dolinski** [lml/commontator#152]
I recently added an autolink gem (https://github.com/vmg/rinku)

On create a comment properly auto links.

On edit it errors out with an undefined method:

```
ActionView::Template::Error (undefined method `rinku_link' for #<#<Class:0x00007fb1e56eec60>:0x00007fb1e71511c0>
Did you mean?  rinku_auto_link):
     5: <%= simple_format comment.is_deleted? ? \
     6:       t('commontator.comment.status.deleted_by',
     7:         deleter_name: Commontator.commontator_name(comment.editor)) : \
     8:         rinku_link(comment.body) %>
```
Btw, rinku_link is the correct helper method name

Perhaps this user was having a similar issue - https://github.com/lml/commontator/issues/55

**Comment by Dantemss** [comment]
Is this a helper method defined in app/helpers? I couldn't find any mention of it in the rinku repo.
If that's the case, I believe you will need to include your helper file (maybe `include ::ApplicationHelper`) in the controller that is serving this view.
If it's really in Rinku, you might have to `include ActionView::Helpers::TextHelper` in that controller probably...

**Comment by Dantemss** [comment]
And/or actually you might have to do this include in `Commontator::ApplicationController`

**Comment by 1dolinski** [comment]
Yes, defined in app/helpers

```
require 'rails_rinku'
include ActionView::Helpers::TextHelper

module TextHelper
    def rinku_link(text)
        auto_link(text, :html => { :target => '_blank' })
    end
end
```

**Comment by Dantemss** [comment]
Yeah you'll need something like `Commontator::ApplicationController.include TextHelper` and probably also include this module in the controller that renders the view where the thread itself appears.

It is a little odd that you have `include ActionView::Helpers::TextHelper` outside of the context of a module though. It's like you are including that module in `main`?

**Comment by 1dolinski** [comment]
Good catch, moved the include into the module. It seems like there might be a reason why the TextHelper is recognized on create but not on edit

**Comment by Dantemss** [comment]
Hmm I think the problem is that the method is being defined in ::TextHelper, not ActionView::Helpers::TextHelper so try `Commontator::ApplicationController.include ::TextHelper` instead. Or `Commontator::ApplicationController.helper ::TextHelper`. Or change your `module TextHelper` to `module ActionView::Helpers::TextHelper` (no need to include it in that case).

**Comment by Dantemss** [comment]
I think Rails may keep gem controllers and helpers separate from the application's by default. Getting gem controllers to use app helpers has always been a little weird to me.

**Comment by 1dolinski** [comment]
For sure -- great so one of your solutions worked out
I added the following in my Commontator initializer 
`Commontator::ApplicationController.helper ::TextHelper`

and then also stripped out the include in the helper

```
require 'rails_rinku'

module TextHelper
    def rinku_link(text)
        auto_link(text, :html => { :target => '_blank' })
    end
end
```
