### ISSUE TITLE
Show Comments(0) not working properly

### ISSUE THREAD

**Issue by mohamed-benali** [lml/commontator#153]
Im using commontator to have comments on my app, but it is not working as it should.
I followed the instructions but when I click on "Show Comments(0)" it redirects me to the correct path but just shows the same as before. Doesnt appear any button of create comment. Its just the same page.
I followed all the instructions, and i dont understand why isn't working for me. 

Tldr: The link is working, but there is no new content to be showed. 
By the way, I'm using Rails 6.0.0 and Ruby 2.6.3p62.

**Comment by mohamed-benali** [comment]
Nevermind, i solved it.
It seems that if i amb using rails 6 i can't install jquery by a gem. I had to do it by a yarn.
If anyone has the same problem, just follow this: 

https://www.botreetechnologies.com/blog/introducing-jquery-in-rails-6-using-webpacker

**Comment by Dantemss** [comment]
Thanks for the heads up. I'll add a note in the readme.
