### ISSUE TITLE
Can't delete an entry due to association

### ISSUE THREAD

**Issue by ghost** [lml/commontator#17]
Hello, the error is:

Cannot modify association 'Movie#subscriptions' because the source reflection class 'Subscription' is associated to 'Commontator::Thread' via :has_many.

I think there is some model rails parameters (like has_many or belongs_to) to write on model(s) that are "commentable", but i'm not sure which can be.

**Comment by sigmike** [comment]
So, having a model both commentable and commentator is not supported?

I have users who can comment other users.
