### ISSUE TITLE
Ruby 2.7 Deprecation Warnings

### ISSUE THREAD

**Issue by alaarab** [lml/commontator#174]
When running Rails 6.0.3.1 and Ruby 2.7.1 I get the following on rails s:

/home/ala/.rvm/gems/ruby-2.7.1/gems/commontator-6.3.0/lib/commontator/acts_as_commontator.rb:22: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

/home/ala/.rvm/gems/ruby-2.7.1/gems/commontator-6.3.0/lib/commontator/acts_as_commontable.rb:20: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

**Comment by alaarab** [comment]
It looks like this is handled in this PR: https://github.com/lml/commontator/pull/173

**Comment by alaarab** [comment]
@Dantemss can you please merge this PR into the official master branch?

**Comment by Dantemss** [comment]
Merged #173
