### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by dannatobigodo** [lml/commontator#179]
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commontator-6.3.0/**lib/commontator/acts_as_commontable.rb:20**: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commontator-6.3.0/**lib/commontator/acts_as_commontator.rb:19**: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commontator-6.3.0/**lib/commontator/acts_as_commontator.rb:22**: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

**Comment by martinstreicher** [comment]
This is fixed by #173 if it can be merged and released.

**Comment by martinstreicher** [comment]
This is a dup of #174

**Comment by Dantemss** [comment]
Merged #173
