### ISSUE TITLE
crashing using ruby version 3.0.0

### ISSUE THREAD

**Issue by merlin2049er** [lml/commontator#182]
NoMethodError: undefined method `arity' for {:dependent=>:destroy, :as=>:creator, :class_name=>"Commontator::Comment"}:Hash
  app/models/user.rb:18:in `<class:User>'
    acts_as_commontator
  app/models/user.rb:3:in `<main>'
    class User < ApplicationRecord
  config/routes.rb:7:in `block in <main>'
    devise_for :users,
  config/routes.rb:3:in `<main>'
    Rails.application.routes.draw do
  config/environment.rb:7:in `<main>'
    Rails.application.initialize!

**Comment by lemingos** [comment]
Just opened PR for that https://github.com/lml/commontator/pull/183

**Comment by Dantemss** [comment]
Merged #173
