### ISSUE TITLE
Error on show.

### ISSUE THREAD

**Issue by marcosteixeira** [lml/commontator#2]
Hi, I got this error. Im using rails 4.

Showing /Users/administrador/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commontator-2.0.1/app/views/commontator/threads/_show.html.erb where line #39 raised:

uninitialized constant Commontator::Thread::Comment

Extracted source (around line #39):  
</span>
<div id="thread_<%= thread.id.to_s %>_comment_list_div" class="thread_comment_list">
     <% thread.ordered_comments.each do |comment| %>
       <% next unless comment.can_be_read_by?(user) %>
       <%= render :partial => 'commontator/comments/show',
                  :locals => {:comment => comment,

**Comment by sebastiz** [comment]
I am getting the error 
I am using Rails 4 and the gem 'commontator', '~> 4.10.0' 

The error reads;

uninitialized constant Commontator

Extracted source (around line #3):
        
Rails.application.routes.draw do
  mount Commontator::Engine => "/app/commontator"
....
end

The stack trace shows:

config/routes.rb:3:in `block in <top (required)>'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:410:in `draw'
config/routes.rb:1:in `<top (required)>'
railties (4.2.2) lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
railties (4.2.2) lib/rails/application/routes_reloader.rb:40:in `each'
railties (4.2.2) lib/rails/application/routes_reloader.rb:40:in `load_paths'
railties (4.2.2) lib/rails/application/routes_reloader.rb:16:in `reload!'
railties (4.2.2) lib/rails/application/routes_reloader.rb:26:in `block in updater'
activesupport (4.2.2) lib/active_support/file_update_checker.rb:75:in `call'
activesupport (4.2.2) lib/active_support/file_update_checker.rb:75:in `execute'
railties (4.2.2) lib/rails/application/routes_reloader.rb:7:in `execute'
railties (4.2.2) lib/rails/application/finisher.rb:81:in `block (2 levels) in <module:Finisher>'
activesupport (4.2.2) lib/active_support/callbacks.rb:446:in `instance_exec'
activesupport (4.2.2) lib/active_support/callbacks.rb:446:in `block in make_lambda'
activesupport (4.2.2) lib/active_support/callbacks.rb:192:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:192:in `block in simple'
activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.2) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_prepare_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:71:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:31:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.2) lib/rails/engine.rb:518:in `call'
railties (4.2.2) lib/rails/application.rb:164:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
This error occurred while loading the following files:
   /home/ubuntu/workspace/config/routes.rb

**Comment by sebastiz** [comment]
I have also tried with /commontator. I am developing using cloud9

**Comment by Dantemss** [comment]
Something odd might be going on with your Gemfile, as it's seems to not be automatically requiring the commontator gem.

You can add require 'commontator' to your routes file at the top, but usually this should not be needed...

**Comment by sebastiz** [comment]
Oh. It looks like all I had to do was restart the server and the error went away....  (blush).
