### ISSUE TITLE
'thread_id' doesn't have a default value: INSERT INTO `commontator_subscriptions`

### ISSUE THREAD

**Issue by ScratZa** [lml/commontator#203]
Hi there 

Hoping someone can assist - I'm quite new to ruby and I'm attempting to upgrade an application to rails 5 (yea its old - i know ) 

running on rails 5.1 now and I seem to be getting this error 
'thread_id' doesn't have a default value: INSERT INTO `commontator_subscriptions`

Have not  changed anything related to commentator - just upgraded the gem to 5.0.0 

Any guidance on how to proceed would be extremely helpful

**Comment by Dantemss** [comment]
Hm does the app have any overridden commontator views, controllers or models? Presumably something is not receiving a Commontator thread object when you try to create a subscription.

**Comment by ScratZa** [comment]
yea I think that was the issue to. After doing a rake commontator:copy which seemed to pull in everything it fixed majority of the issues 

However it does seem im getting the following error on some views "Please use symbols for polymorphic route arguments"
with anything calling commontator.polymorphic_path

**Comment by ScratZa** [comment]
ignore the above - wasnt calling to_sym where necessary :)
