### ISSUE TITLE
Comment nesting

### ISSUE THREAD

**Issue by givingbacksmiles** [lml/commontator#21]
Any thoughts on implementing ancestry for nested comments?  That would tip the scales and make this even more powerful out of the box than it already is.

**Comment by udit7590** [comment]
Yes. Nested comments will really be a great add-on. Is there any plan for it yet?

**Comment by Dantemss** [comment]
Quoting comments is available in 7.0.0.pre.1
I will start working on nesting now.

**Comment by Dantemss** [comment]
Nested comments are available in 6.0.0.pre.2
Please let me know if you have suggestions or find any bugs.

**Comment by Dantemss** [comment]
Merging this issue into https://github.com/lml/commontator/issues/48
If you test the gem, please report any bugs you find over there.
