### ISSUE TITLE
undefined method `current_user'

### ISSUE THREAD

**Issue by MoamenAbdelwahed** [lml/commontator#44]
undefined method `current_user' for #ProductsController:0xc73cce0
 using the method:
  def show
    commontator_thread_show(@product)
  end

stops in
    config/initializers/commontator.rb:15:in `block (2 levels) in <top (required)>'

the line
    config.current_user_proc = lambda { |controller| controller.current_user }

**Comment by piyushbeli** [comment]
I do have a group of users, how can I setup that ? I thought of overiding the Commontator::CommentsController, but in that case how should I changemy routes ?

I short if there are more than one Commentator then how to setup the config ?

Many thanks
Piyush

**Comment by tript** [comment]
I can not make it works. I also have a current_user method in "sesson_helper".
The text "Comment" and "Hide comment" appears. But when i click "new comment", I met this error:
NoMethodError (undefined method `current_user' for #<Commontator::CommentsController:0xb47f9dc4>):
  config/initializers/commontator.rb:15:in `block (2 levels) in <top (required)>'
My config file use: config.current_user_proc = lambda { |controller| controller.current_user }

**Comment by Dantemss** [comment]
The helper is probably not being used by Commontator's controller (gems like Devise usually add the method directly to `ActionController::Base`). You will have to either copy Commontator's controllers into your app and make them use the helper or change your `current_user` method to be available to all controllers.
