### ISSUE TITLE
Issue while creating new post

### ISSUE THREAD

**Issue by ashishevontech** [lml/commontator#47]
I have used this gem for my appliaction and its configured fine.
I have posts and on that each post comments will be given by users.These posts will be created by admin[rails_admin gem].
While creating new post by admin it is giving me following error:
ActionController::UrlGenerationError at /post/new
No route matches {:action=>"show", :controller=>"rails_admin/main", :id=>nil, :model_name=>"commontator~thread"}

Please help me on this?

**Comment by harinsa** [comment]
Still have the same problem in 4.10.5

**Comment by mauriciokj** [comment]
change to 
```
exclude_fields :thread
```

**Comment by Gravity-vV** [comment]
so how did you figure out the issue finally，and i while get the same issue when i add the acts_as_commontable in my model,whats the mean of v4.10.0. is it a gem you published in your repository ? it stuck me several days . now to inquire you. thanks too much  )
