### ISSUE TITLE
Replying

### ISSUE THREAD

**Issue by MoamenAbdelwahed** [lml/commontator#48]
Is it allowable to make user reply on comments ?
and how ?

**Comment by chetankothari** [comment]
We would love to have this feature as well. :+1:

**Comment by JGaudette** [comment]
Any progress on adding replies?

**Comment by ktdmedia** [comment]
+1 for this idea as well.

**Comment by marckohlbrugge** [comment]
Just to confirm there's currently no support for threaded/nested comments, correct? The references to 'comments threads' throughout the documentation would suggest otherwise, but code and issues imply there isn't support for it.

**Comment by Dantemss** [comment]
Each object has its own thread, but replies are not supported yet.

**Comment by marckohlbrugge** [comment]
Ah okay. Thanks!

On Friday, 11 December 2015, Dantemss <notifications@github.com> wrote:

> Each object has its own thread, but replies are not supported yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lml/commontator/issues/48#issuecomment-163999566>.
>


-- 
Sent from iPad

**Comment by vaishnavi3** [comment]
Any progress on this??

**Comment by behindthebid** [comment]
oh man if we could get nested comments working this gem would be 100% perfect.  it already works right off the shelf, just missing that one feature.  having a site without reply / nesting / threading comments is kind of hard to swallow in 2019.  Hopefully this gem is not dead.

**Comment by Dantemss** [comment]
Hm fine, but you better be willing to test the result... also we would likely offer forum-style replies (quoting) for all currently supported databases, but nested comments only on Postgres, MySQL >= 8.0 and whatever other databases support `WITH` clauses (CTEs).

**Comment by behindthebid** [comment]
absolutely!

**Comment by Dantemss** [comment]
Replying to comments (with blockquotes) is available in 6.0.0.pre.1
Please let me know if you have suggestions or find any bugs.

**Comment by Dantemss** [comment]
Nested comments are available in 6.0.0.pre.2
Please let me know if you have suggestions or find any bugs.
I don't expect the migrations for nested comments to change anymore after this version.

**Comment by Dantemss** [comment]
Version 6.0.0 with support for quoting and nested comments has been released, so I'm closing this issue. If you encounter any bugs, please open a new issue.
