### ISSUE TITLE
New comment form not showing when config.new_comment_style = :l

### ISSUE THREAD

**Issue by mark-eda2014** [lml/commontator#50]
I had an issue that sounded similar to #47, but without the javascript error.  If I changed `config.new_comment_style` to `:t`, it worked as expected.  

I found out that the form was rendered, but hidden.  It seems to me that this is because in `app/views/commontator/threads/_reply.html.erb`, `@new_comment` has not been set, even though `commontator_set_new_comment` has been called via `set_thread` due to the `before_filter` in `CommentsController`.  I'm not sure whether `@new_comment` is in a scope that should be visible to the form but I confirmed that it is nil in the form, hence the form being hidden.

It is also unclear to me what happens to the `@comment` created in the new action of the CommentsController, so there seems to be some disconnect there.

Unfortunately I can't check this in a clean clone of your repo due to:

```
Bundler::GemspecError: Could not read gem at /Users/my_user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/cache/actionview-4.1.8.gem. It may be corrupted.
An error occurred while installing actionview (4.1.8), and Bundler cannot continue.
Make sure that `gem install actionview -v '4.1.8'` succeeds before bundling.
```
Not sure what to do about that.

Hope this is helpful.

**Comment by Dantemss** [comment]
Closing. Please open a new issue if still a problem.
