### ISSUE TITLE
Getting error when user not logged in.

### ISSUE THREAD

**Issue by namsterdamus** [lml/commontator#53]
Basically it works perfectly fine when a user is logged in. However when I log out and go to a page with the commentator_thread(@pin) then it breaks with this message.

NoMethodError in PinsController#show
undefined method `is_commontator' for nil:NilClass

The controller currently is as follows
```
  def show
    respond_with(@pin)
    commontator_thread_show(@pin)
  end
```
And the view is as follows:
```
    <div class="panel-body">
    <%= commontator_thread(@pin) %>
    </div>
```
It's pretty basic. My guess was that it requires a current_user to not be nil so my alternative to fixing it was to to just put an if statement to only show the comments if they are logged in but what if I want it to always be visible?

**Comment by Dantemss** [comment]
Closing. Please open a new issue if still a problem.
