### ISSUE TITLE
Commontator Interaction with auto_html gem

### ISSUE THREAD

**Issue by andhof-mt** [lml/commontator#55]
Another great gem, auto_html parses text into links. Generally, its stored in the model of the text you wish to parse.

auto_html comes with a helper method that can be called from a view: <%= auto_html('url') {conditions} %>

Installing commontator alongside auto_html causes rails to throw a no-method error for auto_html. Removing commontator instantly fixes the error.

Is commontator using auto_html or any similar keywords that could be shared in scope?

**Comment by Dantemss** [comment]
Would need more info about this error to fix it.

**Comment by Dantemss** [comment]
A backtrace would be great.

**Comment by Dantemss** [comment]
Closing since no reply.
