### ISSUE TITLE
Can a comment be commentable?

### ISSUE THREAD

**Issue by chetankothari** [lml/commontator#59]
Can we have a model which `acts_as_commentable` and each comment again `acts_as_commentable`.

**Comment by Dacrol** [comment]
Also wondering this, need to create separate comment trees. AKA reddit-style comments.

**Comment by chetankothari** [comment]
This looks like a threads feature. Same as issue #56

**Comment by Dantemss** [comment]
You probably mean #48... I'll see what I can do.

**Comment by Dacrol** [comment]
Much appreciated!
