### ISSUE TITLE
Solution for Apps with existing Subscription Model

### ISSUE THREAD

**Issue by Swolie** [lml/commontator#61]
We already have a Subscription model that is related to the User model.

So when @user.subscription is called, it's causing a conflict with the existing model.

Is there anyway to name space or change it to @user.commontator_subscription for example?

Any help would be great!

**Comment by vaishnavi3** [comment]
having same isuue..Is this implemented yet??
@Swolie could u tell how u resolved this???

**Comment by Dantemss** [comment]
Will be fixed in 7.0.0 (fixed in 7.0.0.pre.1)
