### ISSUE TITLE
undefined method `current_user'

### ISSUE THREAD

**Issue by xeron** [lml/commontator#72]
Getting this error:
```
Started GET "/commontator/threads/1/comments/new" for 127.0.0.1 at 2015-07-07 18:23:36 -0700
Processing by Commontator::CommentsController#new as JS
  Parameters: {"thread_id"=>"1"}
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `current_user' for #<Commontator::CommentsController:0x007f8f62ca4308>):
  config/initializers/commontator.rb:15:in `block (2 levels) in <top (required)>'
```

I don't use devise or any other gem. Just omniauth with custom current_user implementation.

Snippet from my application_controller.rb:

```
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
```

If I move ```current_user``` under ```private``` (as it was before I added commontator) error changes to:

```
NoMethodError (private method `current_user' called for #<ProjectsController:0x007f8f645d4968>):
  config/initializers/commontator.rb:15:in `block (2 levels) in <top (required)>'
  app/controllers/projects_controller.rb:14:in `show'
```

Any suggestions?

**Comment by Dantemss** [comment]
The easiest solution would probably be to define current_user in ActionController::Base

Something like:

ActionController::Base.class_exec do
  helper :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

**Comment by xeron** [comment]
Yes, it helped. Thank you!
