### ISSUE TITLE
No action when 'new comment' is clicked

### ISSUE THREAD

**Issue by mofufu** [lml/commontator#77]
I have followed both the tutorial and the readme, but it seems that every time I click on new comment (or the show comments) nothing happens.  The page reloads and no error is thrown at all, has this happened to anyone else?

Controller of this_plan model:

  def show
    @this_plan = ThisPlan.find(params[:id])
        commontator_thread_show(@this_plan)
  end

In view :
  
<%= commontator_thread(@this_plan) %>

**Comment by Dantemss** [comment]
Sounds like UJS is not working on your app. Make sure jquery and jquery_ujs are required in your `application.js`.

**Comment by mofufu** [comment]
Wow thank you so much for that, I was using a different jquery library for most of the actions and that was indeed causing the conflict.  Thank you very very much for the quick reply - and also for giving us this awesome gem!  

I do appreciate your open-sourceness!
