### ISSUE TITLE
undefined method `current_user'

### ISSUE THREAD

**Issue by jackieyin** [lml/commontator#78]
This error happened when: 
Started GET "/commontator/threads/3" for ::1 at 2015-10-01 02:11:35 -0700
Processing by Commontator::ThreadsController#show as JS
  Parameters: {"id"=>"3"}
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.0ms)

error shows:
NoMethodError (undefined method `current_user' for #<Commontator::ThreadsController:0x007f8c674bad20>):
  config/initializers/commontator.rb:15:in `block (2 levels) in <top (required)>'

my current_user is defined in module SessionHelper, and application_controller.rb include SessionsHelper.  in this case, any advice to solve this issue? Thanks 

FYI:
module SessionsHelper
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

**Comment by Dantemss** [comment]
Hello... since Commontator doesn't use your ApplicationController, the easiest solution is to include the SessionsHelper in ActionController::Base instead of the ApplicationController.

```rb
ActionController::Base.class_exec do
  include SessionsHelper
end
```

**Comment by jackieyin** [comment]
I see the logic here, it works, Thanks so much
