### ISSUE TITLE
undefined method `user_path'

### ISSUE THREAD

**Issue by jikaiy** [lml/commontator#79]
Hi, I try to customize something in **app/views/commontator/comments/_show.html.erb**( **<%= link.blank? ? name : link_to(name, link) %> change to <%= link_to(name, creator) %>** ), basically, I want to make link works. I guess **Commontator.commontator_link** function will return the link of creator, However I don't know where I can find this function. so I try to do **<%= link_to(name, creator) %>**, then this error happend 

ActionView::Template::Error (undefined method `user_path' for #<#<Class:0x007f9079a78f80>:0x007f9079c758b0>): 

I guess this happen due to comment and user under different hierarchy, Any Advice about how to fix this? Thanks!

**Comment by jikaiy** [comment]
also, for now, if I clicked **Show Comments (2)**, it will go to extend thread show page, it that possible that  keeping **Show Comments (2)**  there and once I click it again, it will fold thread show page?

**Comment by jikaiy** [comment]
another question is, why only the latest comment in the thread show **edit** and **delete** action link, is that possible that all the comments made by this user ( who logged in now ) will show **edit** and **delete**? 

Sorry for posting a lot of question, I am a big fan here for your code :)

**Comment by jikaiy** [comment]
for question 1, I guess I can do something with **config.user_link_proc = lambda { |user, app_routes| '' }**, I am not sure how to do here

Sorry for a lot of post, I am a big fan for your code :)

**Comment by Dantemss** [comment]
OK good to hear you solved the first problem :)

I don't quite understand the second problem, though.

**Comment by Dantemss** [comment]
Closing due to no reply.
