### ISSUE TITLE
Permanent Delete?

### ISSUE THREAD

**Issue by DaGraves** [lml/commontator#84]
I see that there was a discussion about this about a year ago and I tried doing the steps in that thread but it didnt seem to work. I'm very new at this so please excuse my amateurnish of all this. I am trying to take away the ability to undelete and when someone clicks delete their comment is gone. Can I do this?

**Comment by Dantemss** [comment]
If what you want is to hide the comments, including the deletion message, look for `config.comment_filter` in the initializer and set it to:

`config.comment_filter = Commontator::Comment.arel_table[:deleted_at].eq(nil)`

By default, though, users cannot undelete comments deleted by someone else (so if a moderator deletes one, it's gone unless the moderator undeletes it).

**Comment by DaGraves** [comment]
I could've sworn I tried that. It worked thank you

**Comment by DaGraves** [comment]
Can I ask you an editing question?

**Comment by Dantemss** [comment]
Ask away.

**Comment by Dantemss** [comment]
Closing since the original issue was solved/inactivity.
