### ISSUE TITLE
How to "pre subscribe" a group of users?

### ISSUE THREAD

**Issue by cpg** [lml/commontator#87]
I would like for users that are participating in a league to be auto-subscribed for messages sent in the league. I.e. everyone gets a message for the first post to the league.

I would like it if you provide some guidance as to how to _minimally_ do this?
(emphasis on minimally, e.g. if it's controllers, which one is the one that has to be kept?)

**Comment by Dantemss** [comment]
Assuming league calls `acts_as_commontable`, whenever you add someone to a league (whatever that means) you can also subscribe them to the thread using `league.thread.subscribe(user)`. Whenever you remove someone from the league, you could also call the unsubscribe method to remove that user from the mailing list.

**Comment by cpg** [comment]
Thanks!
