### ISSUE TITLE
How to use Mentions?

### ISSUE THREAD

**Issue by RST-J** [lml/commontator#90]
Hello,
I updated to the latest version of commontator (btw, great work, thanks) and wanted to try out mentions.
I added the flag and the proc to the initializer but when I type an @ followed by three letters of a user's name nothing happens. Am I missing something?

**Comment by Dantemss** [comment]
Make sure you also added `//= require commontator/application` to your application.js.

**Comment by RST-J** [comment]
I've added this but it does not work in my application though. I also see no request being made in the web console. Where else could I look for the cause? Is there some JavaScript object which should be available in the client console?

**Comment by RST-J** [comment]
Ah, I found the issue. I updated commontable but still had the old views in place which I copied using the `rake commontator:copy:views` command.
