### ISSUE TITLE
initializers/commontator.rb not working

### ISSUE THREAD

**Issue by ragunaru** [lml/commontator#91]
I installed commontator as per the instructions. All works like magic. Now, when I try to change the username and photo displayed through the commontator insitializer, it doesn't work. Any changes I make in the initializer never appear.

I changed the default username to `config.user_name_proc = lambda { |user| user.username }` but to no avail. The comment authors are still being displayed as anons. Is there something I'm missing here or?

Just to clarify, I have my `User` model set as commontator and `Product` model set as commontable, it all works. And the username method exists for the `User` model. Everything works as expected, except the config file.

Any help would be much appreciated.

**Comment by ragunaru** [comment]
I need to specify that copying over and modifying view templates works fine. So I can technically show the username and avatar by adding them manually in the template. It's just weird the config file gets ignored. I tried deleting it and copying it over again with `rake commontator:install:initializers ` but it's the same.

**Comment by Dantemss** [comment]
Did you restart the server process after changing the initializer?

**Comment by ragunaru** [comment]
I did not. But now that I did, I can confirm it's working. Sorry, I didn't even think about restarting but probably should've.
