### ISSUE TITLE
support mongodb and  mongoid

### ISSUE THREAD

**Issue by abnud1** [lml/commontator#92]
I want to ask, what is the status of mongodb support for this project

**Comment by Dantemss** [comment]
Unfortunately I never used MongoDB (terrible, I know...), so I suppose no support exists or is planned, but I'll leave this issue here as a reminder.

**Comment by Dantemss** [comment]
I still have never used mongodb and now with the new comment nesting feature that has its own custom SQL statements this is looking even less likely... But feel free to give it a try and submit a PR if it works
